services:
  wash:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wash.rule=Host(`wash.qntn.io`)"
      - "traefik.http.routers.wash.entrypoints=websecure"
      - "traefik.http.routers.wash.tls.certresolver=letsencrypt"

networks:
  traefik:
    external: true

